import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/providers/'
import { Toaster } from "@/components/ui/sonner"
import Image from 'next/image'
import { MainContent } from '@/components/views/main-content'
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Suspense } from 'react'
import Loading from './loading'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex flex-col min-h-screen">
            <div className="flex-grow mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8">
              <MainContent>
                <Suspense fallback={<Loading />}>
                  {children}
                </Suspense>
              </MainContent>
            </div>
            
            <div className="mx-auto w-full max-w-5xl px-4 sm:px-6 lg:px-8">
              <footer className="py-4 border-t mt-auto">
                <div className="flex justify-end items-center">
                  <p className="text-sm text-gray-500">fourni par <strong>Belou</strong></p>
                  <Image 
                    src="/belou.svg" 
                    alt="Belou Logo" 
                    width={50} 
                    height={50} 
                    className="text-orange-500"
                  />
                </div>
              </footer>
            </div>
          </div>
          <Toaster />
          <SpeedInsights />
        </Providers>
      </body>
    </html>
  )
}
